### PR TITLE
Add a bunch of sites

### PR DESCRIPTION
**Pull request by matmat**

### CODE REVIEW

**Comment by vprelovac** [comment]
@matmat looks great. there is too many to manually review hem - how did you source them?

**Comment by matmat** [comment]
@vprelovac Thanks! They are from various places, mostly from HN and from the nixers newsletters. I did actually go through these manually.

**Comment by vprelovac** [comment]
That is amazing, thanks!

**Comment by vprelovac** [comment]
All of them are live now. https://kagi.com/smallweb

**Pull request merged**
