### PR TITLE
Add samwho.dev to smallweb list

### PR DESCRIPTION
**Pull request by samwho**
This is my own website, which I don't run for financial gain (though I do have a Patreon, unsure if that disqualifies me.)

### CODE REVIEW

**Comment by vprelovac** [comment]
No problem, just as per guidelines when submitting your own site, nominate two other blogs too

**Comment by samwho** [comment]
Have suggested:

- https://manybutfinite.com/ -- an excellent blog on low-level, Linux-based topics.
- http://igoro.com/ -- another excellent low-level systems/programming blog.

Apologies for not reading the guidelines! 🙈

**Comment by samwho** [comment]
Actually they don't pass the recency criteria do they? That's a shame, they're very good. I'll think of another 2.

**Comment by samwho** [comment]
Take 3 😄 

- https://www.paepper.com/blog/ an excellent personal blog about machine learning.
- https://rednafi.com/ the personal blog of Redowan Delowar

**Pull request merged**
