### PR TITLE
Remove non-english feeds from the index

### PR DESCRIPTION
**Pull request by fgiasson**
[Related issue](https://github.com/kagisearch/smallweb/issues/60)

This PR removes a bit more than one hundred sites that have been tagged as non-english ([see related issue for more background information](https://github.com/kagisearch/smallweb/issues/60)).

The list of feeds URLs and their associated (detected) languages are:

```python
[
    ('zh-cn', 'http://azaleasays.com/atom.xml'),
    ('zh-cn', 'http://blog.devtang.com/atom.xml'),
    ('zh-cn', 'http://bobjiang.com/index.xml'),
    ('zh-cn', 'http://einverne.github.io/feed.xml'),
    ('zh-cn', 'http://feeds.feedburner.com/Zhu8'),
    ('zh-cn', 'https://blog.sinzy.net/@why/rss'),
    ('zh-cn', 'https://feeds.feedburner.com/initiative'),
    ('zh-cn', 'https://feihu.me/blog/feed.atom'),
    ('zh-cn', 'https://flujoo.github.io/index.xml'),
    ('zh-cn', 'https://havee.me/rss.xml'),
    ('zh-cn', 'https://leovan.me/index.xml'),
    ('zh-cn', 'https://mazhuang.org/feed.xml'),
    ('zh-cn', 'https://memozine.me/atom.xml'),
    ('zh-cn', 'https://robotkang.cc/feed.xml'),
    ('zh-cn', 'https://searchpcc.com/?feed=rss2'),
    ('zh-cn', 'https://sync.sh/atom'),
    ('zh-cn', 'https://www.4async.com/atom.xml'),
    ('zh-cn', 'https://www.drawrect.com/rss'),
    ('zh-cn', 'https://www.du1ab.one/index.xml'),
    ('vi', 'https://mvjantzen.com/feed'),
    ('vi', 'https://peterhung.org/feed'),
    ('vi', 'https://vnhacker.blogspot.com/feeds/posts/default'),
    ('uk', 'https://poohitan.com/rss'),
    ('tr', 'https://lezizkahve.com/feed'),
    ('tr', 'https://mehmetkose.com.tr/index.xml'),
    ('th', 'https://www.coconews.in.th/feed'),
    ('th', 'https://www.cybersecurityinstitute.biz/feed'),
    ('ta', 'https://psankar.blogspot.com/feeds/posts/default'),
    ('sv', 'http://erikeng.se/rss.xml'),
    ('sl', 'https://trsplet.si/feed'),
    ('sk', 'https://www.kulman.sk/index.xml'),
    ('ru', 'http://feeds.feedburner.com/not-a-kernel-guy'),
    ('ru', 'http://nqst.net/blog/rss'),
    ('ru', 'https://amorgunov.com/feed/feed.xml'),
    ('ru', 'https://feeds.feedburner.com/bronevichok'),
    ('ru', 'https://grishaev.me/feed.xml'),
    ('ru', 'https://vasily.polovnyov.ru/feed.xml'),
    ('pt', 'https://guilhermegarcia.dev/blog/feed.rss'),
    ('pt', 'https://ricardopimen.tel/rss/feed.xml'),
    ('pt', 'https://voxleone.com/feed'),
    ('pt', 'https://www.leandrosf.com/rss'),
    ('pl', 'https://blog.piotrnalepa.pl/feed'),
    ('pl', 'https://plblog.danieljanus.pl/atom.xml'),
    ('pl', 'https://retrofun.pl/pl/feed'),
    ('no', 'http://zespia.tw/atom.xml'),
    ('no', 'https://earth.hoyd.net/feed'),
    ('nl', 'https://anselmolsm.org/feed'),
    ('nl', 'https://eend.nl/blog/rss/feed.xml'),
    ('nl', 'https://kamasys.nl/archivo/feed'),
    ('nl', 'https://nielsgouman.nl/index.xml'),
    ('nl', 'https://www.frank.be/rss'),
    ('nl', 'https://www.leidenmedievalistsblog.nl/feed'),
    ('ko', 'http://keunwoochoi.blogspot.com/feeds/posts/default'),
    ('ko', 'https://blog.fnaith.com/feed'),
    ('ko', 'https://feeds.feedburner.com/revidotblog'),
    ('ko', 'https://www.usefulparadigm.com/feed'),
    ('ja', 'http://compass-blueprint.org/?feed=rss2'),
    ('ja', 'http://rcmdnk.github.io/atom.xml'),
    ('ja', 'https://blog.toshimaru.net/atom.xml'),
    ('ja', 'https://bomani.xyz/rss.xml'),
    ('ja', 'https://feeds.feedburner.com/glidenote'),
    ('ja', 'https://mattn.kaoriya.net/index.rss'),
    ('ja', 'https://nomedojogo.com/?feed=rss2'),
    ('ja', 'https://sekika.github.io/feed.xml'),
    ('ja', 'https://takagi.blog/rss.xml'),
    ('it', 'http://digicult.it/feed/'),
    ('it', 'https://ciroesposito.com/articoli/feed'),
    ('it', 'https://dottorblaster.it/feed'),
    ('it', 'https://tsunaminotes.org/feed.xml'),
    ('it', 'https://www.ctrlmagazine.it/feed'),
    ('fr', 'http://letchap.github.io/atom.xml'),
    ('fr', 'http://plugfr.org/feeds/articles.xml'),
    ('fr', 'https://ache.one/rss.xml'),
    ('fr', 'https://beauty-of-imagination.blogspot.com/feeds/posts/default'),
    ('fr', 'https://blog.isammoc.net/index.xml'),
    ('fr', 'https://blog.naeka.fr/feeds/all.atom.xml'),
    ('fr', 'https://blog.notmyidea.org/feeds/all.atom.xml'),
    ('fr', 'https://dbeley.ovh/index.xml'),
    ('fr', 'https://drhenry.org/feed'),
    ('fr', 'https://grenouille-bouillie.blogspot.com/feeds/posts/default'),
    ('fr', 'https://p4bl0.net/feed/atom'),
    ('fr', 'https://ploum.net/atom.xml'),
    ('fr', 'https://www.deblan.io/RSS'),
    ('fr', 'https://www.mylloon.fr/blog/rss'),
    ('fr', 'https://www.yannpl.me/feed'),
    ('fi', 'https://antonnikolenko.blogspot.com/feeds/posts/default'),
    ('fi', 'https://linja-aho.blogspot.com/feeds/posts/default'),
    ('fi', 'https://miikavonbell.com/fi/index.xml'),
    ('fa', 'http://mehdix.ir/feed.xml'),
    ('fa', 'https://behroozam.com/feed.xml'),
    ('es', 'http://blog.alvarezp.org/feed'),
    ('es', 'http://ropherpanama.github.io/feed.xml'),
    ('es', 'http://sivainvi.es/feed'),
    ('es', 'https://blog.adrianistan.eu/rss.xml'),
    ('es', 'https://danielpecos.com/index.xml'),
    ('es', 'https://leivajd.com/rss.xml'),
    ('es', 'https://midu.dev/index.xml'),
    ('es', 'https://perrodinero.blog/feed.xml'),
    ('es', 'https://pi-comunicacion.com/feed'),
    ('es', 'https://pornohardware.com/./atom.xml'),
    ('es', 'https://www.patrickdap.com/index.xml'),
    ('es', 'https://www.therror.com/feed'),
    ('de', 'http://historisches-fechten-leipzig.github.io/atom.xml'),
    ('de', 'http://prometheus-bildarchiv.de/atom.xml.en'),
    ('de', 'http://www.dbrunner.de/feeds/all.atom.xml'),
    ('de', 'https://anrichter.net/feed.xml'),
    ('de', 'https://autotagebuch.net/feed'),
    ('de', 'https://be-jo.net/feed'),
    ('de', 'https://blog.felixbreidenstein.de/index.xml'),
    ('de', 'https://blog.kanedo.net/feed.xml'),
    ('de', 'https://blog.strubbl.de/index.xml'),
    ('de', 'https://bueltge.de/feed'),
    ('de', 'https://coders-home.de/feed'),
    ('de', 'https://detlef-huettemann.com/index.xml'),
    ('de', 'https://donswelt.de/feed.xml'),
    ('de', 'https://eay.cc/feed'),
    ('de', 'https://heikos.blog/feed'),
    ('de', 'https://hymnos.existenz.ch/feed'),
    ('de', 'https://instant-thinking.de/atom.xml'),
    ('de', 'https://jankremer.eu/index.xml'),
    ('de', 'https://kaiserkiwi.de/feed'),
    ('de', 'https://marcgoertz.de/feed'),
    ('de', 'https://notiz.blog/feed'),
    ('de', 'https://wirres.net/article/rss/full/6/15'),
    ('de', 'https://www.andwil.de/weblog.rss'),
    ('de', 'https://www.bebna.de/index.xml'),
    ('de', 'https://www.frumble.de/blog/feed'),
    ('de', 'https://www.schafe-sind-bessere-rasenmaeher.de/index.xml'),
    ('de', 'https://www.thomas-huehn.de/feed.xml'),
    ('de', 'https://www.webrocker.de/feed'),
    ('cs', 'https://chamik.eu/feed.xml'),
    ('ca', 'https://nobelium.vercel.app/feed'),
    ('bg', 'https://itemelkov.com/rss'),
    ('ar', 'https://ammar-alyousfi.com/feed.xml')
]
```

The code that generated that cleaned, and ordered `smallweb.txt` file [is available here](https://github.com/fgiasson/small-web-dataset/blob/main/small_web_dataset/feeds.py#L336).

### CODE REVIEW

**Comment by vprelovac** [comment]
@fgiasson great job. is there anything else we can do to automate removal of unwanted domains?

**Comment by fgiasson** [comment]
My pleasure.

The simplest short term I think would be to create a new PR check. the `small-web-dataset` project is already a CLI tool, we would only have to add a new function that takes a new `smallweb.txt` file as input, compare it to the one on `main` and then check the new proposed feeds at runtime (download the feed, check the articles, determine the language). If non-english, fails. Once this is in place, we just need to push to tool on PyPi and then to create a new PR check that uses it depending what is in the PR (is the PR touching that file or not).

It is some work, but I think it is the best considering what is currently in place, and that way you will catch most of them before anything else.

**Comment by vprelovac** [comment]
Can you upload the script you used for language detection somewhere?

**Comment by fgiasson** [comment]
Yes, everything is available on that project:

 * [small-web-dataset](https://github.com/fgiasson/small-web-dataset)

I just added a new command line option to validate new feeds in an input file (mean to be the new file within a PR). At the moment, the validation is just regarding the language. Other validation could be added like time of last post, etc.

To test it locally, just do the following:

```bash
pip install small-web-dataset
```

then once installed, put that file on your local file system: [smallweb.txt](https://github.com/kagisearch/smallweb/files/12676442/smallweb.txt)

Then run the following command:

```bash
swd validate-kagi-small-web-index smallweb.txt
```

The output will be:

image

If you want to change something in the code, just keep in mind that the tool is develop using [nbdev](https://nbdev.fast.ai) which is a literate programming framework for Python.

**Pull request merged**
