### PR TITLE
Adding new blogs

### PR DESCRIPTION
**Pull request by umarbutler**
This PR adds the blogs of pg, Blaine Bettinger and myself. The urls are sorted.

### CODE REVIEW

**Comment by vprelovac** [comment]
first one is not a personal blog and second has not been updated since 2015

**Comment by umarbutler** [comment]
The first link `http://www.aaronsw.com/2002/feeds/pgessays.rss` is the RSS feed for [Paul Graham's blog](https://paulgraham.com/), its just that its hosted on Aaron Swartz' website.[^1]

As for Blaine Bettinger's blog, [here](https://thegeneticgenealogist.com/2023/03/16/the-growing-phenomenon-of-the-unlinked-family-cluster/) is a post from 2023. If that's not recent enough, I'm happy to add another link.

[^1]: https://paulgraham.com/rss.html

**Comment by umarbutler** [comment]
I have added a fourth blog, [blog.eladgil.com](https://blog.eladgil.com/).

**Comment by vprelovac** [comment]
Closing as not

**Comment by umarbutler** [comment]
@vprelovac Would you mind sharing what guidelines are not adhered to in order to correct the PR?

**Pull request closed without merging**
