### PR TITLE
Update smallweb.txt

### PR DESCRIPTION
**Pull request by funvill**
https://blog.squix.org/ - Makes some interesting ESP32 hardware projects 
https://mitxela.com/projects/hardware - Makes electronic art projects
https://blog.abluestar.com/ - Art projects that include paper and electronics 

Nothing for sale, personal blogs, updates in the last 12 months

### CODE REVIEW

**Comment by vprelovac** [comment]
commit is pretty large and hard to track?

**Comment by funvill** [comment]
Sorry, my fault again 

> Locate and submit the RSS feed of the website. Place in the file so that it remains sorted.

I sorted the WHOLE list alphabetically to insert my new three links "in order". I assumed that the rest of the list was already sorted. 

I will fix it after lunch. Sorry for the trouble and the extra effort you had to put in.

**Comment by vprelovac** [comment]
This list is already sorted (using linux cli 'sort') it seems that your sorting tool preferes different (case-insenitive perhaps) sort order

**Comment by vprelovac** [comment]
are we doing this? :)

**Comment by funvill** [comment]
Thank you ❤️

**Pull request merged**
