### PR TITLE
Three proposed additions to the small web.

### PR DESCRIPTION
**Pull request by drirmbda**
Three proposed additions to the small web.

### CODE REVIEW

**Comment by vprelovac** [comment]
That is one?

**Comment by drirmbda** [comment]
Apologies for my mess, it's my first time editing directly on Github. Should be three now.

**Comment by vprelovac** [comment]
These is not the tpye of content we want to have in. Aim for personal blogs.

**Comment by drirmbda** [comment]
The blogs were personal, but I see, perhaps already too visible through regular search. You might want to add that as another criterion. In addition, after paging through [kagi small web](https://kagi.com/smallweb) I wonder if this is ever going to start yielding sufficient quality to become worth the search in the first place. At this rate and with such a narrow definition of "small.")

**Pull request closed without merging**
