### PR TITLE
Update smallweb.txt

### PR DESCRIPTION
**Pull request by Tuinslak**
Updated with a couple of blogs.

### CODE REVIEW

**Comment by vprelovac** [comment]
@Tuinslak looking good, just please remove medium.com, not really 'small web'

**Comment by Tuinslak** [comment]
Hey -- well I consider it small web 'writers'. Just using a bigger platform (just as many are using WP or Ghost?).

Taken out for now.

**Comment by Tuinslak** [comment]
@vprelovac is blogspot preferred over medium? I see Up North and Off Grid (https://upnorthandoffgrid.blogspot.com/) is also publishing there.

**Comment by vprelovac** [comment]
Yes, mainly because medium has a paywall and just does not fit small web.

**Comment by Tuinslak** [comment]
Patch updated.

**Pull request merged**
