### PR TITLE
Add amitmerchant.com

### PR DESCRIPTION
**Pull request by amitmerchant1990**

### CODE REVIEW

**Comment by amitmerchant1990** [comment]
Any reason for closure?

**Comment by otherjoel** [comment]
You need to follow the rules in README

**Comment by amitmerchant1990** [comment]
Dude, I was on vacation and hence, no posts for the last 7 days. Why don't you check the frequency before that?

I usually post 15 times a month. But never mind.

**Comment by otherjoel** [comment]
You still didn't read it. The relevant section is [here](https://github.com/kagisearch/smallweb#add-a-site-or-channel-to-the-list). 

Closing the PR had nothing to do with your post frequency, that's just criteria for being shown on the KSW website, not for adding to this list. BTW I'm not with Kagi, just another user.

**Pull request closed without merging**
