### PR TITLE
Update smallweb.txt

### PR DESCRIPTION
**Pull request by pivic**
Added my own blog and two additional blogs as per the rules.

### CODE REVIEW

**Comment by vprelovac** [comment]
Please sort them to correct position

**Comment by pivic** [comment]
@vprelovac sorted!

**Comment by vprelovac** [comment]
They are not properly sorted and one of them is a duplicate

**Comment by pivic** [comment]
I'm sorry, @vprelovac! I messed up again. I hope I've sorted everything this time. Thanks for your time and patience.

**Pull request closed without merging**
