### PR TITLE
Update smallweb.txt

### PR DESCRIPTION
**Pull request by janikvonrotz**

### CODE REVIEW

**Comment by lsomm** [comment]
(I didn't want to be rude, I just found it funny. Your website looks cool and I will open an issue on the forums regarding own website promotion.)

**Comment by vprelovac** [comment]
Yeah , ultimately we care about high quality blogs and the rule was put in place just to prevent the submissions spiraling out of control as they stillr equire manual process to review.

**Comment by janikvonrotz** [comment]
@lsomm No intention of self promotion here. I heard about this effort on HN and simply wanted to be part of it. I've been blogging since 2013 and miss the "old web" where the first search result was always a blog post.

**Comment by vprelovac** [comment]
@janikvonrotz accepted. please add two other sites that are not yours as per updated guidelines

**Pull request merged**
