### PR TITLE
Update smallweb.txt

### PR DESCRIPTION
**Pull request by rosnovsky**
Add three feeds:
- https://rosnovsky.us/feed/feed.xml
- https://harrisroxashealth.com/feed/
- https://nicolesandler.com/feed/

### CODE REVIEW

**Comment by vprelovac** [comment]
second blog feed is empty and third is not really a small web site

**Comment by avipars** [comment]
and first is his own one

**Comment by rosnovsky** [comment]
Apologies, let me double check [Laffy](https://mastodon.social/@GottaLaff)'s correct feed URL, this one appears to no longer work :( She's pretty awesome, I promise!

As for Molly White's web3isgoinggreat... It's a personal project where she posts these ~snarky~ pointy news and comments about web3. Is the issue that it's fairly popular or that it's not a _personal_ blog?

**Comment by rosnovsky** [comment]
@vprelovac Fixed Laffy's feed URL. It's still probably not a good fit since it's a show, and the only text information in the feed is show notes. I removed "Web3 is Going Great" and added two other feeds, hopefully, they better fit the definition of "small web". My apologies again for the broken/wrong links.

@avipars yes, that one is my own blog; I think it's allowed to submit your own feed if you also submit at least two new blogs 🤔 

In any case, if you don't find these blogs worth including, feel free to close this PR.

**Comment by vprelovac** [comment]
Podcast show notes a probably not a good fit. rest is ok.

**Comment by vprelovac** [comment]
Do you want to adjust the PR?

**Comment by rosnovsky** [comment]
My apologies, @vprelovac, for some reason I was under the impression that I've adjusted it already 🤦🏻 

✅ Done!

**Pull request merged**
