### PR TITLE
Update smallweb.txt

### PR DESCRIPTION
**Pull request by RoryLawless**

### CODE REVIEW

**Comment by vprelovac** [comment]
can you provide a reason for each?

**Comment by RoryLawless** [comment]
My apologies, the reasons are in the commit messages. The first is due to newsletter pop up and the second is due to the page being password protected.

**Comment by vprelovac** [comment]
Only the last post seems to be protected, the rest of the blog is fine?

**Comment by RoryLawless** [comment]
You’re right. Happy for that change to be discarded.

**Comment by vprelovac** [comment]
Can you please update the MR

**Comment by RoryLawless** [comment]
MR should be updated

**Pull request merged**
