### PR TITLE
Update smallyt.txt

### PR DESCRIPTION
**Pull request by Cyd0n1a**
A very tiny but weird/unique set of content to amaze and hopefully delight. 🐱‍🏍😎🤘🏻👩🏻‍🚀👩🏻‍🔬🛰🌌🚀💯🧠👀

### CODE REVIEW

**Comment by vprelovac** [comment]
Hmm you seem to have added it twice?

For personal feeds, we require +2 other feeds that are not yours.

**Comment by Cyd0n1a** [comment]
Ah, sorry. Oh, & in that case can I also recommend:

https://www.youtube.com/@UKadventures-wi6vh

&

https://www.youtube.com/@LMC97

❓ 

Sorry I don't know how to retrieve their RSS/XML feeds, it's not a feature I've used on YT in quite a long time. (2011-ish) and the UI has changed a lot since then. 😄

**Comment by Cyd0n1a** [comment]
> Hmm you seem to have added it twice?
> 
> For personal feeds, we require +2 other feeds that are not yours.

@vprelovac

**Comment by vprelovac** [comment]
PR please :)

**Comment by Cyd0n1a** [comment]
Sorry I don't know how to get their channel id's. 😞

**Pull request closed without merging**
